apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 3
  name: sk-dind-deploy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sk-dind
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sk-dind
    spec:
      containers:
      - command:
          - "docker"
          - "run"
          - "-p"
          - "80:80"
          - "httpd:latest"
        image: docker:1.12.6
        imagePullPolicy: Always
        name: docker-cmds
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /sk
          name: sk-dind-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run
          type: ""
        name: docker-sock
      - name: sk-dind-storage
        persistentVolumeClaim:
          claimName: sk-dind-storage
