apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-dind-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dind
  template:
    metadata:
      labels:
        app: docker-dind
    spec:
      containers:
      - name: docker-dind-container
        image: docker:dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: sk-dind-storage
          mountPath: /mnt/sk
      volumes:
      - name: sk-dind-storage
        persistentVolumeClaim:
          claimName: sk-dind-storage
